### ISSUE TITLE
HIP failing to build

### ISSUE THREAD

**Issue by erkinalp** [xuhuisheng/rocm-build#43]
### Environment

| Hardware | description   |
|----------|---------------|
| GPU      | AMD RX 5500XT             |
| CPU      | AMD 5950X            |

| Software | version |
|----------|---------|
| OS       | Ubuntu 22.04.2      |
| ROCm     |  5.5      |
| Python   | 3.10.6 |

### What is the expected behavior

Compilation proceeds normally

### What actually happens

at 18.hip.sh:
```
In file included from /tmp/hip_pch.17620/hip_pch.h:1:
/media/erkinalp/SteamLibrary/ROCm/HIP/include/hip/hip_runtime.h:54:10: fatal error: 'thread' file not found
#include <thread>
         ^~~~~~~~
1 error generated when compiling for gfx1030.
CMake Error at src/CMakeLists.txt:187 (message):
  Failed to embed PCH


-- Configuring incomplete, errors occurred!
```
### How to reproduce

Run the scripts in order.

**Comment by ThatcherC** [comment]
I'm seeing this same error. @erkinalp - did you ever figure this one out?

I looked at the extra directions in https://github.com/xuhuisheng/rocm-build/tree/master/ubuntu2204#18hip which recommended to "comment out thread header. No idea why this caused miopen native_conv.cpp error" which I interpreted as commenting out line 54 in `ROCm/HIP/include/hip/hip_runtime.h` (the place where you saw your error), but after running `18.hip.sh` again, I got a different error relating `cmath`, so I'm not sure I applied the fix as intended. 

@xuhuisheng - is commenting out line 54 the right move? Do you have any other guidance for getting this compile on Ubuntu 22.04? Thanks for putting this repo together!

**Comment by xuhuisheng** [comment]
@ThatcherC 
The current version of build script is for ROCm-5.4.
As I am busy at the end of year, I am prefer to jump to ROCm-5.7 directly, and later support ROCm-6.0.

If you really need ROCm-5.5, my suggestion is follow this forked repo:
<https://github.com/Marandil/rocm-build>

**Comment by erkinalp** [comment]
@ThatcherC I have switched to ROCm 6.0 so no.
